e_shop_django/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('product_module.urls'))
]

product_module/urls.py
from django.urls import path
from . import views


app_name='product'
urlpatterns=[
    path('',views.product_list),
    path('product/<slug:slug>',views.product_detail,name="product_detail")
]

product_module/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator
from django.utils.text import slugify

class Product(models.Model):
    title = models.CharField(max_length=20)
    price = models.IntegerField()
    rating = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)],default=0)
    short_description = models.CharField(max_length=360,null=True)
    is_active = models.BooleanField(default=False)
    slug = models.SlugField(default="",null=False,db_index=True,blank=True)

    def save(self,*args,**kwargs):
        self.slug=slugify(self.title)
        super().save(*args,**kwargs)

    def __str__(self):
        return self.title

    
    

product_module/views.py
from django.shortcuts import render,get_object_or_404
from .models import Product
from django.http import Http404
from django.db.models import Avg

def product_list(request):
    products = Product.objects.all()
    number_of_products = products.count()
    Avg_rating = products.aggregate(Avg("rating"))
    return render(request,'product_module/product_list.html',context={'products':products , 'total_number_of_products': number_of_products , 'average_rating':Avg_rating})

def product_detail(request,slug):
    product = get_object_or_404(Product,slug=slug)
    
    
    return render(request,'product_module/product_detail.html', context={'product':product})

product_module/templates/product_module/product_detail.html
{% extends 'base.html' %}
{% block title %}{{product.title}}{% endblock title %}
{% block content %}
<h1>{{product.title}}</h1>
<h2>price : {{product.price}}</h2>
<p>{{product.short_description}}</p>
{% endblock content %}

product_module/templates/product_module/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}product l{% endblock title %}
{% block content %}
<ul style="list-style: none;">
{% for product in products  %}
<li><a style="color: black; text-decoration: none;" href="{% url 'product:product_detail' slug=product.slug %}">{{product.title}}</a></li>
{% endfor %}
    
</ul>
<hr>
<p>
     total number of products: {{total_number_of_products}}
</p>
<p>
    {{average_rating.rating__avg}}
</p>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>